name: Publish Rules to hub.continue.dev

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/main.yaml

env:
  OWNER_SLUG: continuedev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # # Private to organization blocks
      # - uses: continuedev/continue-publish-action@v1
      #   with:
      #     owner-slug: ${{ env.OWNER_SLUG }}
      #     paths: blocks/private/**
      #     visibility: organization
      #     api-key: ${{ secrets.CONTINUE_API_KEY }}
